import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Text from './components/Text';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className="flex min-h-screen flex-col md:px-24 bg-slate-50">
                    <section className="w-full p-4 bg-gradient-to-r from-slate-50 via-slate-300 to-slate-50 shadow-lg shadow-slate-300 mb-8 mt-4">
                        <a href="/">
                            <Text variant="title">Frontend Reciprocity</Text>
                        </a>
                    </section>
                    {children}
                </main>
            </body>
        </html>
    );
}
